// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bugkghvdlnukijoivryb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1Z2tnaHZkbG51a2lqb2l2cnliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDMzODAsImV4cCI6MjA2NjQxOTM4MH0.98ZKP6E6WoozGQ7C-bPQe7xal14pAJ4jU9BNYaqcNYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);